name: deploy
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: run Deno tests
        run: deno test
      - name: publish to JSR
        run: npx jsr publish
